language: python

python:
  - 2.7

install:
 - sudo apt-get update -qq
 - sudo apt-get install -y pylint pep8 libproj-dev libgeos-dev
 - pip install psycopg2

before_script:
 - psql -c 'create database test_db;' -U postgres
 - psql -c 'CREATE EXTENSION postgis;' -U postgres -d test_db

script:
 - pep8 . --exclude=migrations
 - python setup.py test

email:
- tim@kartoza.com
- akbargumbira@gmail.com
